# Generated by Django 5.2.15 on 2026-06-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('lanes_count', models.IntegerField(default=6)),
                ('regulations_pdf', models.FileField(blank=True, upload_to='regulations/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('registration', 'Приём заявок'), ('in_progress', 'Идут заплывы'), ('finished', 'Завершено')], default='draft', max_length=20)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('birth_year_from', models.IntegerField()),
                ('birth_year_to', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(choices=[('freestyle', 'Кроль на груди'), ('backstroke', 'На спине'), ('breaststroke', 'Брасс'), ('butterfly', 'Баттерфляй'), ('medley', 'Комплекс')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('seeded', 'Заплывы сформированы'), ('finished', 'Завершено')], default='pending', max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
