# Generated by Django 5.2.15 on 2026-06-09 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
        ("teams", "0002_alter_team_city_alter_team_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Подана"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("exel_file", models.FileField(blank=True, upload_to="applications/")),
                ("notes", models.TextField(blank=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="AthleteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preliminary_time", models.DurationField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_manually_added", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.application",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.athlete"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка спортсмена",
                "verbose_name_plural": "Заявки спортсмена",
                "unique_together": {("athlete", "event")},
            },
        ),
        migrations.CreateModel(
            name="Heat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидает"), ("finished", "Завершён")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заплыв",
                "verbose_name_plural": "Заплывы",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="HeatLane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lane", models.IntegerField()),
                ("result_time", models.DurationField(blank=True, null=True)),
                ("dns", models.BooleanField(default=False)),
                ("dnf", models.BooleanField(default=False)),
                ("dsq", models.BooleanField(default=False)),
                (
                    "athlete_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.athleteevent",
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.heat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дорожка",
                "verbose_name_plural": "Дорожки",
                "unique_together": {("heat", "lane")},
            },
        ),
    ]
