# Generated by Django 5.2.15 on 2026-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_application_athleteevent_heat_heatlane"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athleteevent",
            options={
                "verbose_name": "Заявка спортсмена",
                "verbose_name_plural": "Заявки спортсменов",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["order"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="heat",
            options={
                "ordering": ["number"],
                "verbose_name": "Заплыв",
                "verbose_name_plural": "Заплывы",
            },
        ),
        migrations.RenameField(
            model_name="application",
            old_name="exel_file",
            new_name="excel_file",
        ),
        migrations.AddField(
            model_name="athleteevent",
            name="participation_status",
            field=models.CharField(
                choices=[("active", "Участвует"), ("withdrawn", "Снялся")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="athleteevent",
            name="start_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("registration", "Приём заявок"),
                    ("closed", "Заявки закрыты"),
                    ("in_progress", "Идут заплывы"),
                    ("finished", "Завершено"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("seeded", "Заплывы сформированы"),
                    ("in_progress", "Идут заплывы"),
                    ("finished", "Завершено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="heat",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("in_progress", "Идёт"),
                    ("finished", "Завершён"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
