# Generated by Django 5.2.15 on 2026-06-10 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0003_alter_athleteevent_options_alter_event_options_and_more",
        ),
        ("teams", "0002_alter_team_city_alter_team_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="athletes",
                to="competitions.application",
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athletes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="athletes",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
